language: java
sudo: false
install: true
jdk: oraclejdk8
env:
  matrix:
  - TERM=dumbi
addons:
  apt:
    packages:
    - oracle-java8-installer
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - ./gradlew --version
script: ./gradlew -S check test jacocoTestReport
after_success:
  - ./gradlew coveralls

